Fix wrong "subversion" variable for job and batch name
quadproduction/OpenPype pull request #609
Opened 2023-11-24 16:04 UTC by friquette

## Changelog Description
The code for the "subversion" variable was wrong, this should fix it.

## Testing notes:
Send a Maya job on Deadline with subversion and without subversion in the workfile name.

2023-11-27 13:16 UTC, BenSouchet requested changes

2023-11-27 14:12 UTC, friquette commented on openpype/modules/deadline/utils.py
> +    if re.match(r'^_v[0-9]{3}$', subversion):
fixed

2023-11-29 13:10 UTC, BenSouchet commented
@friquette : Just to understand why checking the subversion part of the filename and if there is one setting the subversion to an empty string ?

2023-11-29 13:24 UTC, friquette commented
> @friquette : Just to understand why checking the subversion part of the filename and if there is one setting the subversion to an empty string ?

I did this to avoid having two times the version in the job name if there is no subversion

2023-11-29 13:44 UTC, BenSouchet commented
But your current code is `IF there is a subversion, remove it`.
This differ from `IF there is NOT a subversion, remove it`.

Do you have a screenshot of the wrong behavior occurring, when you doesn't want the subversion field.

2023-11-29 15:34 UTC, friquette commented
> But your current code is `IF there is a subversion, remove it`. This differ from `IF there is NOT a subversion, remove it`.
> 
> Do you have a screenshot of the wrong behavior occurring, when you doesn't want the subversion field.

No, it says, ```IF the subversion looks like a version, remove it```
This was why the job name in the ticket had the version at the end though in the settings it was the subversion at the end

2023-11-29 15:45 UTC, BenSouchet commented
> > But your current code is `IF there is a subversion, remove it`. This differ from `IF there is NOT a subversion, remove it`.
> > Do you have a screenshot of the wrong behavior occurring, when you doesn't want the subversion field.
> 
> No, it says, `IF the subversion looks like a version, remove it` This was why the job name in the ticket had the version at the end though in the settings it was the subversion at the end

Okay, I misunderstood the purpose of the subversion attribute, after looking up, it's a suffix/comment to differentiate or add info to a version.

2023-11-30 14:57 UTC, closed without merging

2023-11-30 14:57 UTC, BenSouchet commented
Merged in `3.16.9-quad-1.1.0`, will be available when we release it this week.