#326: enhancement: add 'rename_layers' photoshop function
quadproduction/OpenPype pull request #698
Opened 2024-03-08 15:48 UTC by Guilhemz

## Changelog Description
Add Photoshop route to rename list of layers.

Fix quadproduction/issues#326

## Additional info
Each entry needs to have an 'id' corresponding to the layer id to rename and a 'new_name' which contains the new name of the layer.

2024-03-13 09:02 UTC, BenSouchet requested changes

2024-03-13 09:04 UTC, BenSouchet commented
Et le mieux serait de revert les changements car il y a plein de lignes qui ont été reformatées alors que pas nécessaire (au pire se reformatage devrait être fait dans un commit séparé, mais pas avec des modifs "logic")

2024-03-15 11:14 UTC, Guilhemz commented
Merci pour tes retours @BenSouchet ,
Concernant les changements sur le script `client.js` je ne sais pas pourquoi ils ont eu lieu. C'est peut-être un coup de Visual Studio Code qui aurait pu appliquer un formattage auto, mais j'ai cherché dans les préférences et il n 'y a rien de setté à ce niveau là. Je suspecte plutôt Git qui aurait pu agir sur le fichier (notamment via l'action `trim trailing whitespace` qui est lancée automatiquement lors d'un commit).

Pour l'instant j'ai simplement récupéré la structure du fichier de base et ajouté ma fonction uniquement via l'éditeur inclus dans Github, mais on aura probablement le soucis de nouveau à la prochaine modification du fichier.

2024-03-15 11:19 UTC, Guilhemz commented on openpype/hosts/photoshop/api/extension/extension.zxp
J'ai replacé le fichier au bon endroit, attention cependant, il faudra de toute façon regénéré entièrement le fichier d'extension en prenant aussi en compte les modifications d'Hadrien sur sa PR (https://github.com/quadproduction/OpenPype/pull/699)

2024-03-15 11:25 UTC, Guilhemz commented on openpype/hosts/photoshop/api/extension/extension.zxp
Ah non pardon, le commit ne s'est pas bien fait. 
En revanche, problème de mon côté, Git refuse de considérer le fichier comme nouveau et ne veut pas le pusher.
Dans la mesure où, de toute façon, il faudra générer une nouvelle version de l'extension à partir de la prochaine mise en prod, ça ne me paraît pas obligatoire de pusher le fichier

2024-03-15 17:18 UTC, BenSouchet commented
> Merci pour tes retours @BenSouchet , Concernant les changements sur le script `client.js` je ne sais pas pourquoi ils ont eu lieu. C'est peut-être un coup de Visual Studio Code qui aurait pu appliquer un formattage auto, mais j'ai cherché dans les préférences et il n 'y a rien de setté à ce niveau là. Je suspecte plutôt Git qui aurait pu agir sur le fichier (notamment via l'action `trim trailing whitespace` qui est lancée automatiquement lors d'un commit).
> 
> Pour l'instant j'ai simplement récupéré la structure du fichier de base et ajouté ma fonction uniquement via l'éditeur inclus dans Github, mais on aura probablement le soucis de nouveau à la prochaine modification du fichier.

D'acc, pour info, il est possible de skip les hooks de git via l'ajout du flag `--no-verif` lors des `git commit` et des `git push`

2024-03-19 10:00 UTC, closed without merging