533: enhancement: Ajout d'une option pour desactiver le set de resolu…
quadproduction/OpenPype pull request #769
Opened 2024-07-11 15:20 UTC by hfarre

Fix quadproduction/issues#533
## Changelog Description
Ajout d'une option pour desactiver le set de resolution à l'ouverture de Nuke

2024-08-13 08:34 UTC, BenSouchet requested changes

2024-08-13 08:34 UTC, BenSouchet commented on openpype/hosts/nuke/api/lib.py
> +        if self._get_set_resolution_startup():
Avec cette condition l'entrée nommé `Set Custom Resolution` dans le menu ne marche plus si le set_resolution_startup est désactivé (`false`), à voir avec @ccaillot pour trouver une meilleure manière de faire, potentiellement mettre une condition dans la méthode `add_nuke_callbacks`

2024-08-13 14:35 UTC, hfarre commented on openpype/hosts/nuke/api/lib.py
> +        return custom_settings.get("hosts", {}).get("nuke", None).get("set_resolution_startup", True)
Clean

2024-08-13 14:36 UTC, hfarre commented on openpype/hosts/nuke/api/lib.py
> +        if self._get_set_resolution_startup():
Je viens de faire une proposition en ajoutant un arg quand la fonction est lancé depuis le menu dans Nuke.
Si cela ne convient pas je passe la main à @ccaillot  ^^

2024-08-14 15:53 UTC, ccaillot commented on openpype/hosts/nuke/api/lib.py
> +        if self._get_set_resolution_startup():
Effectivement je pense que l'utilisation des callbacks de Nuke simplifierait pas mal de chose et notamment la passation de l'arg, je travaille dessus

2024-08-19 13:13 UTC, hfarre commented on openpype/hosts/nuke/api/lib.py
> +        if self._get_set_resolution_startup():
Je test ça, mais pour une raison obscure, je n'ai que la ligne 183 du fichier pipeline.py qui est pull
Et c'est la seule ligne modifié dans l'onglet file changed ^^'
Une idée de où seraient passés le reste des modif ?

2024-08-19 13:38 UTC, hfarre commented on openpype/hosts/nuke/api/lib.py
> +        if self._get_set_resolution_startup():
Ok, j'ai fait une mini correction, car en l'etat, le toogle des custom_plugin n'affecté pas le set de résolution au démarage.
Il n'appliquait pas la custom_resolution, mais appliqué tjr la resolution du projet

2024-08-19 14:10 UTC, merged