Enhancement/412 enhancement validator noms uniques tvpaint
quadproduction/OpenPype pull request #773
Opened 2024-08-01 15:17 UTC by hfarre

Fix quadproduction/issues#412

Check si des layers ont le meme nom et les selectionne au besoin pour reparation manuel

2024-08-12 15:53 UTC, BenSouchet commented on openpype/hosts/tvpaint/plugins/publish/validate_layers_name_uniqueness.py
> +                if layer_list.count(layer["name"]) == 1:
On pourrait aussi faire:
```python
if layer["name"] in duplicates or layer_list.count(layer["name"]) == 1:
```

2024-08-12 16:13 UTC, BenSouchet requested changes

2024-08-13 08:30 UTC, hfarre commented on openpype/hosts/tvpaint/plugins/publish/validate_layers_name_uniqueness.py
> +                    msg = "{}\nThe name {} is not unique.".format(msg, layer["name"])
Si, car en premier, dans le format, je renvoie le msg deja existant, donc à chaque passage dans la boucle, les noms non uniques se cumulent

2024-08-13 08:32 UTC, hfarre commented on openpype/hosts/tvpaint/plugins/publish/validate_layers_name_uniqueness.py
> +                if layer_list.count(layer["name"]) == 1:
Correction appliquée

2024-08-13 08:32 UTC, hfarre commented on openpype/hosts/tvpaint/plugins/publish/validate_layers_name_uniqueness.py
> +    Change instanace metadata in the workfile.
Correction appliquée

2024-08-13 08:32 UTC, hfarre commented on openpype/hosts/tvpaint/plugins/publish/validate_layers_name_uniqueness.py
> +    """Repair the asset names.
Correction appliquée

2024-08-19 14:09 UTC, merged