Enhancement/539 enhancement playblast blender en rgba
quadproduction/OpenPype pull request #774
Opened 2024-08-05 10:33 UTC by hfarre

Fix quadproduction/issues#539

Permettre de faire des png playblasts avec alpha avec un toogle d'option dans le tool. Par défaut activé.

2024-08-13 09:26 UTC, BenSouchet requested changes
Je pense que le nom de la variable devrait être `use_transparent_bg` au lieu de `make_bg_transparency`

2024-08-13 09:26 UTC, BenSouchet commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +    make_bg_transparency: bpy.props.BoolProperty(name="Alpha BG")
`use_transparent_bg: bpy.props.BoolProperty(name="Use Transparent Background")`

2024-08-13 09:26 UTC, BenSouchet commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +        col.prop(context.scene, 'make_bg_transparency')
`col.prop(context.scene, 'use_transparent_bg')`

2024-08-13 09:26 UTC, BenSouchet commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +        make_bg_transparency = context.scene.make_bg_transparency
`use_transparent_bg = context.scene.use_transparent_bg`

2024-08-13 09:26 UTC, BenSouchet commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +        if make_bg_transparency:
`if use_transparent_bg:`

2024-08-13 09:26 UTC, BenSouchet commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +        if make_bg_transparency:
if `use_transparent_bg:`

2024-08-13 09:26 UTC, BenSouchet commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +    bpy.types.Scene.make_bg_transparency = bpy.props.BoolProperty(default=True)
`bpy.types.Scene.use_transparent_bg = bpy.props.BoolProperty(default=True)`

2024-08-13 09:26 UTC, BenSouchet commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +    del bpy.types.Scene.make_bg_transparency
`del bpy.types.Scene.use_transparent_bg`

2024-08-13 15:42 UTC, hfarre commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +    make_bg_transparency: bpy.props.BoolProperty(name="Alpha BG")
Corrigé

2024-08-13 15:42 UTC, hfarre commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +        col.prop(context.scene, 'make_bg_transparency')
Corrigé

2024-08-13 15:42 UTC, hfarre commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +        make_bg_transparency = context.scene.make_bg_transparency
Corrigé

2024-08-13 15:42 UTC, hfarre commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +        if make_bg_transparency:
Corrigé

2024-08-13 15:42 UTC, hfarre commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +        if make_bg_transparency:
Corrigé

2024-08-13 15:43 UTC, hfarre commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +    bpy.types.Scene.make_bg_transparency = bpy.props.BoolProperty(default=True)
Corrigé

2024-08-13 15:43 UTC, hfarre commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +    del bpy.types.Scene.make_bg_transparency
Corrigé

2024-08-14 11:22 UTC, ccaillot commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +    make_bg_transparency: bpy.props.BoolProperty(name="Alpha BG")
Tu as changé le nom de la variable mais pas le label du BoolProperty qui est toujours 'Alpha BG', est-ce intentionnel de ta part ?

2024-08-14 12:43 UTC, hfarre commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +    make_bg_transparency: bpy.props.BoolProperty(name="Alpha BG")
Youpsy

2024-08-14 12:45 UTC, hfarre commented on openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
> +    make_bg_transparency: bpy.props.BoolProperty(name="Alpha BG")
C'est commit

2024-08-19 14:31 UTC, merged