412: enhancement: correction du code pour inclure TOUS les layers aya…
quadproduction/OpenPype pull request #788
Opened 2024-09-12 12:41 UTC by hfarre

…nt le meme nom dans la liste de selection retournee et amelioration de l'affichage du msg pour ne prendre en compte quune seule fois le nom en duplicata

Fix quadproduction/issues#412

2024-09-13 13:06 UTC, ccaillot requested changes

2024-09-13 13:06 UTC, ccaillot commented on openpype/hosts/tvpaint/plugins/publish/validate_duplicated_layer_names.py
> +        print(context.data['transientData'][ValidateLayersGroup.__name__])
eneleve ton print

2024-09-13 13:06 UTC, ccaillot commented on openpype/hosts/tvpaint/plugins/publish/validate_duplicated_layer_names.py
>          raise PublishXmlValidationError(
est-ce que le raise ne va pas bloquer l'action ?

2024-09-13 13:06 UTC, ccaillot commented on openpype/hosts/tvpaint/plugins/publish/validate_duplicated_layer_names.py
> +            "\n\"{}\"".format(layer_name)
Version simplifiée : 

layers_msg = ",\n ".join(duplicated_layer_names)

2024-09-13 13:10 UTC, hfarre commented on openpype/hosts/tvpaint/plugins/publish/validate_duplicated_layer_names.py
>          raise PublishXmlValidationError(
Non car plus haut tu as:
```
        # Everything is OK and skip exception
        if not duplicated_layer_names:
            return
```

Qui permet d'arrêter le process si y a pas d'erreur detecté

2024-09-13 13:10 UTC, hfarre commented on openpype/hosts/tvpaint/plugins/publish/validate_duplicated_layer_names.py
> +        print(context.data['transientData'][ValidateLayersGroup.__name__])
youps

2024-09-13 13:11 UTC, hfarre commented on openpype/hosts/tvpaint/plugins/publish/validate_duplicated_layer_names.py
> +            "\n\"{}\"".format(layer_name)
Oui on peut simplifier l'existant, ça coute rien d'ameliorer le code d'OP

2024-09-16 11:59 UTC, BenSouchet commented
@ccaillot à voir pour gérer le conflit et merge dans la 1.16.0, car tu as update la PR de la 1.16.0 mais tu as pas merge cette PR

2024-09-16 12:16 UTC, ccaillot commented
yes, je regarde ça dans la journée, sinon demain

2024-09-17 09:02 UTC, merged

2024-09-17 09:02 UTC, ccaillot commented
c'est mergé